language: php
dist: trusty
env:
  global:
    - TRAVIS_NODE_VERSION="10"
    - COMPOSER_ROOT_VERSION=3.x-dev

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: DB=MYSQL RECIPE_VERSION=4.3.x-dev PHPUNIT_TEST=1

before_script:
  - composer self-update || true
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  - composer validate
  - composer install --prefer-dist
  - composer require --no-update silverstripe/recipe-cms:"$RECIPE_VERSION"
  #- composer require --prefer-dist --no-update silverstripe/recipe-core:4.x-dev silverstripe/versioned:1.x-dev silverstripe/assets:1.x-dev --prefer-dist
  #- composer require --prefer-dist --no-update silverstripe/recipe-core:"$RECIPE_VERSION" silverstripe/versioned:1.x-dev silverstripe/assets:1.x-dev --prefer-dist
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:2.1.x-dev; fi

  # Install NPM dependencies
  - if [[ $NPM_TEST ]]; then nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION && npm install -g yarn && yarn install --network-concurrency 1 && (cd vendor/silverstripe/admin && yarn install --network-concurrency 1) && yarn run build; fi

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ tests/ *.php; fi
  - if [[ $NPM_TEST ]]; then git diff-files --quiet -w --relative=client; fi
  - if [[ $NPM_TEST ]]; then git diff --name-status --relative=client; fi
  - if [[ $NPM_TEST ]]; then yarn coverage; fi
  - if [[ $NPM_TEST ]]; then yarn lint; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml -F php; fi
  - if [[ $NPM_TEST ]]; then bash <(curl -s https://codecov.io/bash) -F js; fi
